### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by MudasirSherwani**
## We have finished the code work on unit testing in this branch :

- [ ] Add Test for Person ✔️ 
- [ ] Add Test for Teacher✔️
- [ ] Add Test for Student✔️
- [ ] Add Test for  Rental✔️
- [ ] Add Test for  Classroom✔️
- [ ] Add Test for Books✔️
- [ ] Add Test for Capitalize✔️
- [ ] Add Test for Decorator✔️
- [ ] Add Test for Trimmer✔️
- [ ] Add Test for Base Decorator✔️
- [ ] Update README file✔️
- [ ] Fix Linters✔️

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

You have submitted a project that has no linter setup. Please make sure all linters are set up and passing before your next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AshakaE — APPROVED** [review]
Hi @Osoro254Alex & @MudasirSherwani , 

### Highlights ✨ 

- Code base looks clean 👍 
- Pull request description 👌 
- Well done testing the ruby classes 👏 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AshakaE** [comment]
Kindly fix the linter errors, also kindly stop pushing code when you submit for code reviews

Thanks

**Comment by MudasirSherwani** [comment]
>

**Comment by MudasirSherwani** [comment]
@AshakaE 
Sir linters are fixed now, 
I apologize for the confusion during the code review.

**Comment by AshakaE** [comment]
> @AshakaE Sir linters are fixed now, I apologize for the confusion during the code review.

No problem 👍

**Pull request merged**
